-- TRIGGERS.sql

------------------------------------------------------------
-- Trigger 1: Log Customer Updates
------------------------------------------------------------

CREATE TABLE Customer_Audit (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CustomerID NUMBER,
    Action VARCHAR2(50),
    ActionDate DATE
);

CREATE OR REPLACE TRIGGER CustomerUpdateTrigger
AFTER UPDATE ON Customers
FOR EACH ROW
BEGIN
    INSERT INTO Customer_Audit(CustomerID, Action, ActionDate)
    VALUES(:OLD.CustomerID, 'Customer Updated', SYSDATE);
END;
/

------------------------------------------------------------
-- Trigger 2: Prevent Negative Balance
------------------------------------------------------------

CREATE OR REPLACE TRIGGER CheckBalanceTrigger
BEFORE UPDATE OF Balance ON Accounts
FOR EACH ROW
BEGIN
    IF :NEW.Balance < 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
        'Account Balance Cannot Be Negative');
    END IF;
END;
/

------------------------------------------------------------
-- Trigger 3: Display Message After Insert
------------------------------------------------------------

CREATE OR REPLACE TRIGGER CustomerInsertTrigger
AFTER INSERT ON Customers
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('New Customer Added Successfully.');
END;
/

------------------------------------------------------------
-- Trigger 4: Automatically Set Created Date
------------------------------------------------------------

CREATE OR REPLACE TRIGGER SetCreatedDate
BEFORE INSERT ON Customers
FOR EACH ROW
BEGIN
    :NEW.CreatedDate := SYSDATE;
END;
/

------------------------------------------------------------
-- Trigger 5: Log Employee Salary Changes
------------------------------------------------------------

CREATE TABLE Salary_Audit (
    EmployeeID NUMBER,
    OldSalary NUMBER,
    NewSalary NUMBER,
    UpdatedOn DATE
);

CREATE OR REPLACE TRIGGER SalaryUpdateTrigger
AFTER UPDATE OF Salary ON Employees
FOR EACH ROW
BEGIN
    INSERT INTO Salary_Audit
    VALUES(
        :OLD.EmployeeID,
        :OLD.Salary,
        :NEW.Salary,
        SYSDATE
    );
END;
/

------------------------------------------------------------
-- Sample Execution
------------------------------------------------------------

UPDATE Customers
SET Balance = Balance + 5000
WHERE CustomerID = 101;

UPDATE Employees
SET Salary = Salary + 3000
WHERE EmployeeID = 101;

COMMIT;